# Generated by Django 4.2 on 2025-01-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
