# Generated by Django 4.2 on 2025-01-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_postcommets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcommets',
            name='profile',
        ),
    ]
