# Generated by Django 4.2 on 2025-01-03 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_postcommets_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommets',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.post'),
        ),
    ]
